# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibble" do
  name "nibble"
  desc "Fast local network scanner with hardware identification and a terminal UI"
  homepage "https://github.com/saberd/nibble"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibble"

  on_macos do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_amd64.tar.gz"
      sha256 "976665290b388105715a3052dd92201b4cba34794ee1f081f2c091eda269705d"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_arm64.tar.gz"
      sha256 "c28097021bb7f57795a79e4ad0417735d7475e4e6101a2d87b48b6a5d8923b5a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_amd64.tar.gz"
      sha256 "b20013c7ad7909956bb2a6efe31df72b15f5a2a229c8f2c35419783042b22300"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_arm64.tar.gz"
      sha256 "962dacf5181b113fb13205d043d4f7df93c13a2d799f725f017d019d6eb68c25"
    end
  end

  # No zap stanza required
end
