# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibble" do
  name "nibble"
  desc "Fast local network scanner with hardware identification and a terminal UI"
  homepage "https://github.com/saberd/nibble"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibble"

  on_macos do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_amd64.tar.gz"
      sha256 "85ed111a08fff75150a691fe33d0e2928f634c13e74083e0e79d3ecf08637927"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_arm64.tar.gz"
      sha256 "cb75412557a697488e453b4a52dedc8f2e66f13b8cc9acacda3ec4e078152835"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_amd64.tar.gz"
      sha256 "e5606c64f2508a3d2fba44b46f9884fc59541c0fe9cd48e066c6f979bab774b6"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_arm64.tar.gz"
      sha256 "fb0efbddf8f15e8ec18489a6416326b142da56cb8ce7a9709fa1ea34371f67b8"
    end
  end

  # No zap stanza required
end
