# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibble" do
  name "nibble"
  desc "Fast local network scanner with hardware identification and a terminal UI"
  homepage "https://github.com/saberd/nibble"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibble"

  on_macos do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_amd64.tar.gz"
      sha256 "4ed7f5020d8e6a32fb696de204a531ae3409911deadadaae4bd0323c7a931b12"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_darwin_arm64.tar.gz"
      sha256 "176068fd821d96bf2cf30eb39ffa39d9e700d7e947a9f6cdd5ba095899bd4e70"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_amd64.tar.gz"
      sha256 "dabc17c1137304db975522155843795db5a7f95c4ab5598f07d6d7aaacb77406"
    end
    on_arm do
      url "https://github.com/saberd/nibble/releases/download/v#{version}/nibble_linux_arm64.tar.gz"
      sha256 "54deaf6774385ad811f57452c5e1a615457f732e55fb16b93f8f486fc80c300a"
    end
  end

  # No zap stanza required
end
